Add ZIP 320 test vectors.
zcash/zcash-test-vectors pull request #97
Opened 2024-04-22 02:13 UTC by nuttycom

2024-04-23 18:35 UTC, daira commented on pyproject.toml
> +zip_0320 = "zcash_test_vectors.zip_0320:main"
Should this be in the transparent module?

2024-04-23 18:35 UTC, daira commented on test-vectors/json/zip_0320.json
> +    ["From https://github.com/zcash-hackworks/zcash-test-vectors/blob/master/unified_address.py"],
This comment string is wrong.

2024-04-23 18:37 UTC, daira commented on zcash_test_vectors/transparent/zip_0320.py
> +    return bytes(convertbits(data, 6, 8, False))
```suggestion
    return bytes(convertbits(data, 5, 8, False))
```

2024-04-23 18:38 UTC, daira commented on zcash_test_vectors/zip_0320.py
> +        'unified_address',
This is wrong.

2024-04-23 18:39 UTC, daira requested changes
Changes needed.

2024-04-23 19:00 UTC, nuttycom commented
[force-pushed](https://github.com/zcash/zcash-test-vectors/compare/6167963..439d5a3) to address comments from code review.

2024-04-23 23:25 UTC, daira commented on test-vectors/json/zip_0320.json
> +    ["From https://github.com/zcash-hackworks/zcash-test-vectors/blob/master/transparent/zip_0320.py"],
This URL is not correct, it should be https://github.com/zcash/zcash-test-vectors/blob/master/zcash_test_vectors/transparent/zip_0320.py

2024-04-23 23:27 UTC, daira approved these changes
utACK modulo the still-incorrect URLs.

2024-04-24 19:29 UTC, daira approved these changes
utACK

2024-04-24 19:30 UTC, merged